source:
    rootUrl: http://maven.aliyun.com/nexus/content/groups/public/

walker:
    filter:
        enabled: true

dest:
    downloadDir: E:\\HanYu_WorkDir\\mvnRepo

executor:
    pool:
        corePoolSize: 20
        maximumPoolSize: 20
        keepAliveTime: 30
        
redown:
    redown: false
    missingLog: missingUrl.log
    waterLine: 5000
    downloadLimit: 1000